{{- if .Values.keycloak.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: {{ include "curq.fullname" . }}
  annotations:
    edp.epam.com/preserve-resources-on-deletion: {{ .Values.keycloak.realm.preserveOnDelete | quote }}
spec:
  realmName: {{ .Values.keycloak.realm.name | quote }}
  keycloakRef:
    name: {{ include "curq.fullname" . }}
    kind: Keycloak
{{- end }}
