{{/* Generate a secret for the Keycloak client if no existing secret is provided */}}
{{- if and .Values.keycloak.enabled (not .Values.keycloak.clientSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-keycloak-client" (include "curq.fullname" .) }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: {{ .Values.keycloak.clientSecret.key | quote }}
{{- end }}
