apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "runboat.serviceAccountName" . }}
  namespace: {{ .Values.runboat.buildNamespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "patch", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "patch", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "patch", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "patch", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "patch", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "patch", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "patch", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "patch", "get", "list", "watch", "delete", "deletecollection"]
---
{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runboat.fullname" . }}
  namespace: {{ .Values.runboat.buildNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "runboat.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "runboat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
