{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "curq.fullname" . }}
  labels:
    {{- include "curq.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts: 
      - {{ .Values.ingress.host | quote }}
      secretName: {{ include "curq.fullname" . }}-tls
    {{- range .Values.ingress.extraHosts }}
    - hosts:
      - {{ . | quote }}
      secretName: {{ printf "%s-tls-%s" (include "curq.fullname" $) (. | replace "." "-") }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: {{ include "curq.fullname" . }}
                port:
                  name: http
          - pathType: ImplementationSpecific
            path: "/websocket"
            backend:
              service:
                name: {{ include "curq.fullname" . }}
                port:
                  name: websocket
    {{- range .Values.ingress.extraHosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: {{ include "curq.fullname" $ }}
                port:
                  name: http
          - pathType: ImplementationSpecific
            path: "/websocket"
            backend:
              service:
                name: {{ include "curq.fullname" $ }}
                port:
                  name: websocket
    {{- end }}
{{- end }}
