{{- if and .Values.persistence.enabled .Values.persistence.volume.create }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "curq.fullname" . }}
  labels:
    {{- include "curq.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }} # When using S3 the storage is virtually unlimited, this value is required but ignored by the S3 CSI driver
  accessModes:
    - {{ .Values.persistence.volume.accessMode | default .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: {{ .Release.Namespace }}
    name: {{ include "curq.fullname" . }}
  mountOptions:
    {{ - with .Values.persistence.volume.mountOptions }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  csi:
    driver: {{ .Values.persistence.volume.csiDriver }}
    volumeHandle: {{ include "curq.fullname.namespaced" . }}
    volumeAttributes:
      {{- with .Values.persistence.volume.volumeAttributes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
