{{- if .Values.s3.create }}
apiVersion: s3.onestein.nl/v1
kind: Bucket
metadata:
  name: {{ include "curq.fullname" . }}
  labels:
    {{- include "curq.labels" . | nindent 4 }}
spec:
  name: {{ .Values.s3.bucketName | quote }}
  secret: {{ .Values.s3.secret.name | quote }}
  accessKey: {{ .Values.s3.secret.accessKey | quote }}
  secretKey: {{ .Values.s3.secret.secretKey | default "secretKey" | quote }}
  endpointKey: {{ .Values.s3.secret.endpointKey | default "endpoint" | quote }}
  deletionPolicy: {{ .Values.s3.deletePolicy | default "Always" | quote}}
{{- end }}
