{{- if not .Values.databaseManager.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "curq.fullname" . }}-db-manager
  labels:
    {{- include "curq.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
{{- end }}
