{{- if not .Values.databaseManager.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-manager" (include "curq.fullname" .) }}
  labels:
    {{- include "curq.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
---
{{- end }}
{{- if and .Values.database.name .Values.admin.update }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin-user" (include "curq.fullname" .) }}
  labels:
    {{- include "curq.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
{{- end }}
