{{/* Generate a password for the catch-all mailbox if no existing secret has been supplied */}}
{{- if and .Values.mailcow.enable (not .Values.mailcow.catchallSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "curq.fullname" . }}-catchall
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data: {}
{{- end }}
