{{/* Postgres default super user password */}}
{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "curq.fullname" . }}-postgres
  labels:
    {{- include "curq.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
---
{{- end }}
{{/* Database role password, only generated if the role is created and no existing secret is provided */}}
{{- if and .Values.database.role.create (not .Values.database.role.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "curq.fullname" . }}-postgres-role
  labels:
    {{- include "curq.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
---
{{- end }}
